<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HSWEBDEV323" name="Test" tests="3" failures="1" timestamp="18 Jan 2016 12:15:54 GMT" time="103.1" errors="0">
  <testcase name="verifyLoginLogoutThree on [Test: &quot;null&quot; verbose:1[parameters:][metagroups:] [included: ][excluded: ]  classes: packages:] " time="24.693" classname="Tests.LoginTestThree"/>
  <testcase name="verifyLoginLogout on [Test: &quot;null&quot; verbose:1[parameters:][metagroups:] [included: ][excluded: ]  classes: packages:] " time="25.428" classname="Tests.LoginTestFour"/>
  <testcase name="verifyLoginLogoutTwo on [Test: &quot;null&quot; verbose:1[parameters:][metagroups:] [included: ][excluded: ]  classes: packages:] " time="91.618" classname="Tests.LoginTestTwo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at Tests.LoginTestTwo.verifyLoginLogoutTwo(LoginTestTwo.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verifyLoginLogoutTwo on [Test: "null" verbose:1[parameters:][metagroups:] [included: ][excluded: ]  classes: packages:]  -->
</testsuite> <!-- Test -->
